In [26]:
print("Hello, World!")

Hello, World!


In [27]:
print("Bienvenidos a las prácticas de Python")

Bienvenidos a las prácticas de Python


Este es un segmento de texto
#Títulos
#Subtítulos
## Otros Subtítulos

In [28]:
nombre = "Juan"
edad = 25
altura = 1.80
es_estudiante = True


In [29]:
print(edad)

25


In [30]:
print(altura)

1.8


In [31]:
print(f"El ususario se llama {nombre}, tiene {edad} años de edad, mide {altura} metros")

El ususario se llama Juan, tiene 25 años de edad, mide 1.8 metros


In [32]:
mi_numero = 10
print(f"Número original: {mi_numero}")

mi_numero = 60
print(f"Número nuevo: {mi_numero}")

Número original: 10
Número nuevo: 60


In [33]:
num_int1 = 123
num_int2 = -57

In [34]:
num_float1 = 3.14
num_float2 = -0.16

In [35]:
bool_var1 = True
bool_var2 = False

In [36]:
bool_var1

True

In [37]:
bool_var1
bool_var2

False

In [38]:
bool_var2
bool_var1

True

In [39]:
print(bool_var1)
print(bool_var2)

True
False


In [40]:
list_numbers = [1, 2, 3, 4, 5]
list_strings = ["A", "B", "C", "D"]

In [41]:
list_strings[0]

'A'

In [42]:
list_numbers[0]

1

Para una lista (suponer que se llama X)
 
     X = [a1, a2, a3, a4, ..., an]
posicion:  0   1  2    3 ..... n-1


In [43]:
list_strings[2]

'C'

## Operadores

In [44]:
x = 5
y = 3

z = x + y  # Salida: z = 8
print(z)

z = x * y  # Salida: z = 15
print(z)

8
15


In [45]:
x = 5
y = 3

z = x + y  # Salida: z = 8
print(f"El resultado de la suma es {z}")

z = x * y  # Salida: z = 15
print(f"El resultado del producto {z}")

El resultado de la suma es 8
El resultado del producto 15


Operadores logicos

In [46]:
True and False

False

In [47]:
True or False

True

In [48]:
not False

True

In [49]:
not not True

True

## Estructura de decision 

Si 
if "REGLA":
     Se coloca la instruccion/operacion que hara la maquina


In [50]:
edad = 45
if edad >= 18:
    print("Eres mayor de edad.")

Eres mayor de edad.


In [51]:
edad >= 18

True

Sino , complemente si

si (condicion):

    Lo que haga el programa
en caso contrario
   
   lo que deba hacer

In [52]:
edad = 45
if edad >= 18:
    print("Eres mayor de edad.")
else:
    print("No eres mayor de edad.")

Eres mayor de edad.


In [53]:
edad = 12
if edad >= 18:
    print("Eres mayor de edad.")
else:
    print("No eres mayor de edad.")

No eres mayor de edad.


elif es una extensión del if

In [54]:
X = [1,2,3,4,5,6,7,8,9,10]
X



[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [55]:
X[9]

10

In [56]:
20/2

10.0

In [57]:
20%2

0

In [58]:
if X[0] % 3 == 0:
    print("El numero es divisible por 3 y su resto es 0")
elif X[0] % 3 == 1:
    print("El numero no es divisible por 3 y su resto es 1")
else:
    print("el numero no es divisible por 3 y su resto es 2")

El numero no es divisible por 3 y su resto es 1


In [59]:
j = 5

if X[j] % 3 == 0:
    print("El numero es divisible por 3 y su resto es 0")
elif X[j] % 3 == 1:
    print("El numero no es divisible por 3 y su resto es 1")
else:
    print("el numero no es divisible por 3 y su resto es 2")

El numero es divisible por 3 y su resto es 0


In [60]:
X[j]

6

### Estructuras de repeticion

In [61]:
for i in range(5):
    print(i)

0
1
2
3
4


In [62]:
frutas = ["manzana", "banana", "cereza"]

for x in frutas:
    print(x)


manzana
banana
cereza


In [63]:
X

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [64]:
# Tratar de modificar la estructura para que funcione y diga si los elementos de X son divisible por 3

for j in X:
    if j % 3 == 0:
        print(f"El número {j} es divisible por 3 y su resto es 0")
    elif j % 3 == 1:
        print(f"El número {j} no es divisible por 3 y su resto es 1")
    else:
        print(f"El número {j} no es divisible por 3 y su resto es 2")


El número 1 no es divisible por 3 y su resto es 1
El número 2 no es divisible por 3 y su resto es 2
El número 3 es divisible por 3 y su resto es 0
El número 4 no es divisible por 3 y su resto es 1
El número 5 no es divisible por 3 y su resto es 2
El número 6 es divisible por 3 y su resto es 0
El número 7 no es divisible por 3 y su resto es 1
El número 8 no es divisible por 3 y su resto es 2
El número 9 es divisible por 3 y su resto es 0
El número 10 no es divisible por 3 y su resto es 1


### Mientras


Mientras 

while (condicion):

    Lo que haga el programa

   
   condicion auxiliar (condicion)
         
    

### longitud o tamaño de una lista 
'len' permite saber la cantidad de elementos de una lista


In [65]:
X

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [66]:
len(X) 

10

la instrccion 'type' permite identificar el tipo de objeto que estamos trabajando 

In [67]:
type(X)

list

In [68]:
X1 = (1,2,3,4,5,6,7,8,9,10)

In [69]:
type(X1)

tuple

In [70]:
len(X1)

10

In [71]:
X2 = {"1","2","3","4","5","6","7","8","9","10"}

In [72]:
type(X2)

set

In [73]:
len(X2)

10

In [74]:
X

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [75]:
X[4]

5

Cada vez que se coloca X[j] estamos indicandole al programa que me muestre el elementos de X esta en la posicion j

In [76]:
j = 3 
X[j]

4

In [77]:
X1

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

In [78]:
X1[2]

3

In [79]:
X2

{'1', '10', '2', '3', '4', '5', '6', '7', '8', '9'}

In [80]:
X2[2]

TypeError: 'set' object is not subscriptable

Tarea investigar como llamar a un elemento de un conjunto en python

In [ ]:
contador = 0

while contador < 5:
    print(contador)
    contador = contador + 1

0
1
2
3
4


In [ ]:
contador = 0

while contador < 5:
    print(contador)
    contador += 1

0
1
2
3
4


In [ ]:
for j in X:
    if j % 3 == 0:
        print(f"El número {j} es divisible por 3 y su resto es 0")
    elif j % 3 == 1:
        print(f"El número {j} no es divisible por 3 y su resto es 1")
    else:
        print(f"El número {j} no es divisible por 3 y su resto es 2")


El número 1 no es divisible por 3 y su resto es 1
El número 2 no es divisible por 3 y su resto es 2
El número 3 es divisible por 3 y su resto es 0
El número 4 no es divisible por 3 y su resto es 1
El número 5 no es divisible por 3 y su resto es 2
El número 6 es divisible por 3 y su resto es 0
El número 7 no es divisible por 3 y su resto es 1
El número 8 no es divisible por 3 y su resto es 2
El número 9 es divisible por 3 y su resto es 0
El número 10 no es divisible por 3 y su resto es 1


In [ ]:
# X = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

i = 0
while i < len(X):
    j = X[i]
    if j % 3 == 0:
        print(f"El número {j} es divisible por 3 y su resto es 0")
    elif j % 3 == 1:
        print(f"El número {j} no es divisible por 3 y su resto es 1")
    else:
        print(f"El número {j} no es divisible por 3 y su resto es 2")
    i += 1  # i = i + 1
    


El número 1 no es divisible por 3 y su resto es 1
El número 2 no es divisible por 3 y su resto es 2
El número 3 es divisible por 3 y su resto es 0
El número 4 no es divisible por 3 y su resto es 1
El número 5 no es divisible por 3 y su resto es 2
El número 6 es divisible por 3 y su resto es 0
El número 7 no es divisible por 3 y su resto es 1
El número 8 no es divisible por 3 y su resto es 2
El número 9 es divisible por 3 y su resto es 0
El número 10 no es divisible por 3 y su resto es 1


In [ ]:
continuar = True
suma = 0

while continuar == True:
    suma = suma + 5
    print(suma)
    if suma == 45:
        continuar = False 

5
10
15
20
25
30
35
40
45


In [ ]:
continuar = True
suma = 0

while continuar == True:
    suma = suma + 5
    if suma == 45:
        continuar = False 
        print(suma)

45


# NumPy

*NumPy* es un juego de palabras que significa Python numérico (Numerical Python). Es una librería de código abierto que se utiliza para llevar a cabo tareas matemáticas con altísima eficiencia. Además, introduce estructuras de datos como los arrays multidimensionales, que se pueden operar entre ellos a alto nivel, sin meterse mucho en el detalle.

In [ ]:
import numpy as np


In [ ]:
# Generar un arreglo unidimensional

x1 = np.array([10,9,8,7,6,5,4,3,2,1])
x1

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
# Observar una posición en particular

x1[2]

np.int64(8)

In [ ]:
print(x1[2])

8


In [ ]:
print(f"El valor ubicado en la posición 2 es: {x1[2]}")

El valor ubicado en la posición 2 es: 8


In [ ]:
# Ajustar un valor en particular

x1[0] = 0

print(x1)

[0 9 8 7 6 5 4 3 2 1]


In [ ]:
x1

array([0, 9, 8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
# x1 + k; k = 10

x1 = x1 + 10
x1

array([10, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [ ]:
x1 += 10  # x1 = x1 + 10
x1

array([20, 29, 28, 27, 26, 25, 24, 23, 22, 21])

In [ ]:
# Consolidar los valores contenidos en el x1 ( np.sum() ) 

suma_x1 = np.sum(x1)
print(f"La suma de todos los elementos de x1 es igual a: {suma_x1}")

La suma de todos los elementos de x1 es igual a: 245


In [ ]:
suma_x1

np.int64(245)

In [ ]:
len(x1)

10

In [ ]:
# Calculemos el promedio de los elementos de x1

n = len(x1)
promedio = suma_x1/n
print(f"el promedio de los elementos de x1 es igual a: {promedio}")

el promedio de los elementos de x1 es igual a: 24.5


In [ ]:
# si usamos la definición de NumPy ( np.mean() )

print(f"el promedio de los elementos de x1 es igual a: {np.mean(x1)}")

el promedio de los elementos de x1 es igual a: 24.5


In [ ]:
# Operaciones aritmeticas ( ( np.add(nombre del arreglo, numero con el cual operaremos)) )

# suma en numpy
x2 = np.add(x1,-10)
x2


array([10, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [ ]:
# Multiplicación 

x1

array([20, 29, 28, 27, 26, 25, 24, 23, 22, 21])

In [ ]:
x1*2

array([40, 58, 56, 54, 52, 50, 48, 46, 44, 42])

In [ ]:
# np.multiply(nombre del arreglo, numero con el cual operaremos)
np.multiply(x1,2)

array([40, 58, 56, 54, 52, 50, 48, 46, 44, 42])

In [ ]:
# mediana

np.median(x1)

np.float64(24.5)

In [ ]:
# Desviacion estandar np.median()
np.std(x1)

np.float64(2.8722813232690143)

In [ ]:
# Varianza np.var()
np.var(x1)

np.float64(8.25)

In [ ]:
# Minimo y Maximo 

# el comando np.argmin() permite conocer el indice donde se ubica el valor minimo

minimo = np.argmin(x1)
print(f"El valor minimo de x1 se ubica en la posicion {minimo}")

# el valor minimo del arreglo se busca con np.min()
min_x1 = np.min(x1)
print(f"El valor mas pequeño de x1 es {min_x1}")

# el comando np.argmax() permite conocer el indice donde se ubica el valor maximo

maximo = np.argmax(x1)
print(f"El valor maximo de x1 se ubica en la posicion {maximo}")

# el valor maximo del arreglo se ubica con np.max()
max_x1 = np.max(x1)
print(f"El valor mas grande de x1 es {max_x1}")



El valor minimo de x1 se ubica en la posicion 0
El valor mas pequeño de x1 es 20
El valor maximo de x1 se ubica en la posicion 1
El valor mas grande de x1 es 29


In [85]:
x1

array([20, 29, 28, 27, 26, 25, 24, 23, 22, 21])

In [87]:
# Funciones de Redondeo